services:
  experiment-platform-pseudolab-frontend:
    build:
      context: .
      dockerfile: ./frontend/Dockerfile
    container_name: experiment-platform-pseudolab-frontend
    ports:
      - "8081:80"
    restart: always

  experiment-platform-pseudolab-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: experiment-platform-pseudolab-backend
    ports:
      - "8000:8000"
    restart: always
    env_file:
      - ./backend/.env
